### ISSUE TITLE
Config Failing - any ideas ?

### ISSUE THREAD

**Issue by beeper99** [hakt0-r/homebridge-platform-linktap#3]
Hi So glad to see this module, but can't seem to get it to work.

I enter the platform config exactly as described - modify all the details (I know they are right as I can trigger taps with AppleScript) but when Homebridge is launched I get this error:

SyntaxError: Unexpected token / in JSON at position 726
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Any idea?

**Comment by beeper99** [comment]
My Problem, I was pasting the example code in first, deleting fixed it.
